### PR TITLE
moved stats, whiteboard to commons

### PR DESCRIPTION
**Pull request by stillalex**

### CODE REVIEW

**Comment by rhudea** [comment]
What happens with the org.apache.jackrabbit.oak.stats exported from oak-core ? Is it a problem?

**Comment by stillalex** [comment]
hmm, should move to oak-commons

**Comment by rombert** [comment]
I was looking at `spi.whiteboard` recently since it's a dependency for `spi.gc`. It's a pretty mixed package, so what makes it a candidate for oak-api as opposed to oak-commons? Not arguing for one or the other, just trying to understand the reasoning.

**Comment by stillalex** [comment]
whiteboard moved to oak-commons, not sure what you mean?

**Comment by stillalex** [comment]
ok @rhudea I moved the package export to oak-commons

**Comment by rombert** [comment]
@stillalex - I meant why choose oak-commons for the whiteboard stuff instead of oak-api

**Comment by stillalex** [comment]
@rombert good question. it doesn't really look like an api to me, if you look at the classes, whiteboard is an abstraction over OSGi services, a poor man's dependency injection mechanism.

**Comment by stillalex** [comment]
Fixed a bunch of broken imports, and now AEM is broken because oak-core needs `junit.framework -- Cannot be resolved` package, but I'm not sure this was introduced by my changes

**Comment by rombert** [comment]
@stillalex - thanks for the explanation.

To fix the JUnit imports, it seems that you need to remove the 'old' imports from oak-core

```
diff --git a/oak-core/pom.xml b/oak-core/pom.xml
index 5ecb619fc7..83d3f45489 100644
--- a/oak-core/pom.xml
+++ b/oak-core/pom.xml
@@ -94,9 +94,7 @@
               org.apache.jackrabbit.oak.spi.security.user.action,
               org.apache.jackrabbit.oak.spi.security.user.util,
               org.apache.jackrabbit.oak.spi.state,
-              org.apache.jackrabbit.oak.spi.whiteboard,
               org.apache.jackrabbit.oak.spi.xml,
-              org.apache.jackrabbit.oak.stats,
               org.apache.jackrabbit.oak.query,
               org.apache.jackrabbit.oak.query.fulltext,
               org.apache.jackrabbit.oak.query.facet,
```

**Comment by anchela** [comment]
regarding the spi.whiteboard package: i created OAK-6034<https://issues.apache.org/jira/browse/OAK-6034> to move the user-related Whiteboard* classes to oak.security.user... that really doesn't need to reside in an spi package... don't ask me why it ended up there.

kind regards
angela

**Comment by stillalex** [comment]
I think it's looking pretty good. I need to wait for OAK-6035, OAK-6036, OAK-6034 to reach github so I can rebase the PR on top of that, but it seems there are no more errors on my end.
(edit) I'm also hitting OAK-6033 quite regularly, we should also include that fix in our fork once it is available.

**Pull request merged**
