### PR TITLE
Start removal of the o.a.j.o.util package

### PR DESCRIPTION
**Pull request by rombert**
The util package is a collection of various helper classes and base implementations. Being not very cohesive it's not easy to move altogether.

This PR moves most of the classes out of it.

Comments very welcome, I tried to find the best locations for the classes but probably went wrong with some of them :-)

### CODE REVIEW

**Comment by anchela** [comment]
looks very good to me...
opened and fixed https://issues.apache.org/jira/browse/OAK-6044 wrt missing private constructor in OakVersion, which btw is a nightmare, isn't it?

**Comment by stillalex** [comment]
looks good!

**Review by stillalex — APPROVED** [review]
looks good

**Comment by rombert** [comment]
Thanks! I'll rebase on top of the latest changes and then merge.

**Comment by rombert** [comment]
Rebased on top of the latest changes and waiting for the local full ITs to complete.

**Comment by rombert** [comment]
Travis is still building, but since all tests pass locally I will merge.

**Pull request merged**
